### ISSUE TITLE
Attributes?

### ISSUE THREAD

**Issue by ronsmith** [btimby/py-radius#4]
There doesn't seem to be any way to set attributes on the authenticate request. Am I just missing it?

**Comment by btimby** [comment]
I have rewritten this library and it now fully supports Attributes. You can reference them by name or by constants defined in the lib. Here is an example of authenticating using an Attribute.

```python
import radius

radius.authenticate('secret', 'username', 'password', attributes={
    'Service-Type': 'foo'
})
# -- or --
radius.authenticate('secret', 'username', 'password', attributes={
    radius.ATTR_SERVICE_TYPE: 'foo'
})
```

Some caveats are:
- I am validating these, thus only attributes defined in the RFC are currently allowed.
- Reading attributes from the reply will require using a lower-level interface than `authenticate()`.
- Multiples of the same attribute are allowed (as the RFC states). Thus the dictionary that holds attributes returns a `list` of values rather than a single value.

Example low-level usage:

```python
import radius

r = radius.Radius('secret', 'host', 1812)

# access_request() is a shortcut, tou could optionally build your own radius.Message().
m = radius.access_request('secret', 'username', 'password')

with r.connect() as c:
    # Serialize and send the data.
    c.send(m.pack())

    # This blocks!
    recv = c.recv(radius.MAX_PACKET)

    # This validates that the reply matches the request.
    m = m.verify(recv)

print(m.code)
print(m.attributes.items())
```

Of course you must poll or wait for the reply using `select()` or similar if you don't want to block forever. See `radius.py` for more details on the low-level API.
